#!/bin/bash

#script para modificacao das portas para in ou out
#ultima modificacao: 01-06-2014

WORK_DIR="/sys/class/gpio/gpio"

if [ "$#" -lt "2" ]; then
echo "usage: GPIODIR [gpio] [option]"
echo ""
echo "[gpio]      - gpio number"
echo ""
echo "[option]    - in : set gpio_number as input"
echo "            - out: set gpio_number as output"
else
echo "$2" > ${WORK_DIR}${1}/direction
fi

