#!/bin/bash

#script para leitura do nivel das portas
#ultima modificacao: 01-06-2014

WORK_DIR="/sys/class/gpio/gpio"

if [ "$#" -lt "1" ]; then
echo "usage: GPIOPIN [gpio]"
echo ""
echo "[gpio]      - gpio number"
echo ""
echo "read the status of  gpio_number. Return [1/0]"
else
cat  ${WORK_DIR}${1}/value
fi

