#!/bin/bash

#script para modificacao das portas para in ou out
#ultima modificacao: 01-06-2014

WORK_DIR="/sys/class/gpio"

if [ "$#" -lt "2" ]
then
echo "usage: GPIOCON [gpio_number] [option]"
echo ""
echo "[gpio]      - gpio number"
echo ""
echo "[option]    - c : create alias gpio_number in /sys/class/gpio"
echo "            - d : delete alias gpio_number in /sys/class/gpio"

else

if [ $1 = "c" ]
then
echo ${2} > ${WORK_DIR}/export
fi

if [ $1 = "d" ]
then
echo ${2} > ${WORK_DIR}/unexport
fi

fi



